[project]
name = "python-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.0",
    "pre-commit>=4.2.0",
    "pylint>=3.3.7",
    "ruff>=0.12.2",
    "uvicorn>=0.35.0",
]
