name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install fastapi uvicorn psutil pydantic
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Run ruff
      run: |
        ruff check .
    # - name: code coverage
    #   run: |
    #     coverage run -m pytest
    #     coverage report